---
title: "Indices of deprivation 2019: Greater Manchester"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library("flexdashboard")
library("readxl")
library("tidyverse")
library("sf")
library("leaflet")
library("DT")

imd_2019 = read_excel("../data/raw/File_1_-_IMD2019_Index_of_Multiple_Deprivation.xlsx", 
     sheet = "IMD2019")

# Keep only GM data
la_codes = c("E08000001", "E08000002", "E08000003", "E08000004", "E08000005",
               "E08000006", "E08000007", "E08000008", "E08000009", "E08000010")

imd_2019_gm =
  imd_2019 %>%
  filter(`Local Authority District code (2019)` %in% la_codes) 
```

Column {data-width=650}
-----------------------------------------------------------------------

### Map of Greater Manchester, coloured by IMD decile

The darker areas represent the more deprived areas.

```{r, echo = FALSE, message = FALSE, warning = FALSE}
geo = st_read("../data/raw/Lower_Layer_Super_Output_Areas_December_2011_Boundaries_EW_BSC/Lower_Layer_Super_Output_Areas_December_2011_Boundaries_EW_BSC.shp", quiet = TRUE)

# Keep only GM data
lsoa_codes = imd_2019_gm$`LSOA code (2011)`

geo_gm =
  geo %>%
  filter(LSOA11CD %in% lsoa_codes)

imd_geo = 
  left_join(geo_gm, imd_2019, by = c("LSOA11CD" = "LSOA code (2011)"))

pal = colorNumeric(palette = "YlOrBr", domain = imd_geo$`Index of Multiple Deprivation (IMD) Decile`, reverse = TRUE)

leaflet(imd_geo) %>%
  addTiles() %>%
  addPolygons(fillColor = ~pal(`Index of Multiple Deprivation (IMD) Decile`), 
              label = ~`LSOA name (2011)`, 
              weight = 1,
              opacity = 1,
              color = "grey",
              dashArray = "1",
              fillOpacity = 0.9) %>%
      addLegend("bottomleft", pal = pal, values = ~`Index of Multiple Deprivation (IMD) Decile`,
    title = "IMD decile")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Table of GM LSOAs arrange by rank

```{r}
imd_2019_gm %>%
  select(`LSOA name (2011)`, `Index of Multiple Deprivation (IMD) Rank`) %>%
  arrange(`Index of Multiple Deprivation (IMD) Rank`) %>%
  datatable()
```

### GM neighbourhoods in the most deprived 10% of neighbourhoods in England

```{r}

# Calculate what percentage of the GM neighbourhoods are in the 
# most deprived 10 per cent of neighbourhoods in England

percent_most_deprived = 
  imd_2019_gm %>%
  group_by(`Index of Multiple Deprivation (IMD) Decile`) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n)) %>%
  filter(`Index of Multiple Deprivation (IMD) Decile` == 1) %>%
  pull(freq) 

valueBox(paste0(round(100 * percent_most_deprived), "%"), icon = "fa-home")
```


